name: Java CI with Maven
on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Build with Maven 1
      run: mvn -B package --file pom.xml
    - name: Build with Maven 2
      run: mvn -B package --file pom.xml
    - name: Build with Maven 3
      run: mvn -B package --file pom.xml
    - name: Run JUnit Tests
      run: mvn test
    - name: Archive JUnit Test Report
      uses: actions/upload-artifact@v2
      with:
        name: junit-test-report
        path: target/surefire-reports/*.xml
    - name: Stage
      run: mkdir staging && cp target/*.jar staging
    - name: Run JAR files
      run: |
        for jar_file in staging/*.jar; do
